version: '3.8'

services:
  # Serviço do Laravel (PHP + FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - db

  # Serviço Nginx
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # Serviço MySQL
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Define a senha do usuário root
      MYSQL_DATABASE: laravel             # Cria o banco de dados 'laravel'
      MYSQL_USER: laravel_user            # Cria um usuário regular 'laravel_user'
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - db

networks:
  laravel_network:

volumes:
  db_data:
